version: "3.5"

services:
  network-monitor:
    restart: always
    build: ./appv2
    environment:
      MONGOURL: mongodb://mongo:27017/
    networks:
      - basicsetup_some-net
networks:
  basicsetup_some-net:
    external: true